---
- name: Install and configure httpd
  hosts: all
  become: true

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create index.html file
      copy:
        content: "<html><body><h1>This web server 1 deployed by AWX</h1></body></html>"
        dest: /var/www/html/index.html
